package agent

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderMermaidGeneratesHTML(t *testing.T) {
	env := testEnv(t)
	tool := &renderMermaidTool{}

	// Missing diagram input
	res, _ := tool.Run(context.Background(), env, map[string]any{"diagram": ""})
	if !res.IsError {
		t.Fatalf("expected error for empty diagram")
	}

	// Generate diagram HTML with open_browser false
	diagram := "graph TD\n  Client --> Server\n  Server --> Database"
	customOut := filepath.Join(env.Workspace, "arch.html")
	res, err := tool.Run(context.Background(), env, map[string]any{
		"diagram":      diagram,
		"title":        "System Architecture",
		"open_browser": false,
		"output_path":  "arch.html",
	})
	if err != nil || res.IsError {
		t.Fatalf("renderMermaid failed: %v, out: %s", err, res.Output)
	}

	data, err := os.ReadFile(customOut)
	if err != nil {
		t.Fatalf("failed to read generated HTML: %v", err)
	}
	content := string(data)
	if !strings.Contains(content, "System Architecture") {
		t.Errorf("expected title in HTML, got:\n%s", content)
	}
	if !strings.Contains(content, "Client --&gt; Server") && !strings.Contains(content, "Client --> Server") {
		t.Errorf("expected diagram in HTML, got:\n%s", content)
	}
	if !strings.Contains(content, "mermaid.esm.min.mjs") {
		t.Errorf("expected mermaid loader in HTML, got:\n%s", content)
	}
}

func TestBrowserOpenValidation(t *testing.T) {
	env := testEnv(t)
	tool := &browserOpenTool{}

	// Empty url
	res, _ := tool.Run(context.Background(), env, map[string]any{"url": ""})
	if !res.IsError {
		t.Fatalf("expected error for empty url")
	}

	// Non-existent local file
	res, _ = tool.Run(context.Background(), env, map[string]any{"url": "non-existent-file.html"})
	if !res.IsError {
		t.Fatalf("expected error for non-existent local file")
	}

	// Local file outside workspace refused
	res, _ = tool.Run(context.Background(), env, map[string]any{"url": "../outside.html"})
	if !res.IsError {
		t.Fatalf("expected error for file outside workspace")
	}

	// Refuse dangerous executable file extension
	dummyExe := filepath.Join(env.Workspace, "test.exe")
	if err := os.WriteFile(dummyExe, []byte("MZ"), 0o755); err != nil {
		t.Fatal(err)
	}
	res, _ = tool.Run(context.Background(), env, map[string]any{"url": "test.exe"})
	if !res.IsError {
		t.Fatalf("expected error for executable file")
	}
}

func TestRenderMermaidWorkspaceEscapeRefused(t *testing.T) {
	env := testEnv(t)
	tool := &renderMermaidTool{}

	res, _ := tool.Run(context.Background(), env, map[string]any{
		"diagram":     "graph TD\n  A --> B",
		"output_path": "../outside.html",
	})
	if !res.IsError {
		t.Fatalf("expected error for output_path outside workspace")
	}
}

func TestFindBrowserExecutable(t *testing.T) {
	bin, err := findBrowserExecutable()
	if err != nil {
		t.Logf("No browser found in test environment: %v", err)
		return
	}
	if bin == "" {
		t.Errorf("expected non-empty browser binary path")
	}
	if _, err := os.Stat(bin); err != nil {
		t.Errorf("detected browser binary does not exist on disk: %s", bin)
	}
}

func TestBuildMermaidHTMLTheme(t *testing.T) {
	htmlOut := buildMermaidHTML("Test Diagram", "sequenceDiagram\n  Alice->>Bob: Hello")
	if !strings.Contains(htmlOut, "#0f141c") {
		t.Errorf("expected dark theme background in HTML")
	}
	if !strings.Contains(htmlOut, "Generated by Termixgo") {
		t.Errorf("expected branding badge in HTML")
	}
}
